# Generated by Django 4.2.13 on 2025-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_visitlog_created_at_visitlog_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
