# Generated by Django 4.2.13 on 2025-08-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_agent_walletsubmission_phrase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletsubmission',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RenameField(
            model_name='walletsubmission',
            old_name='wallet',
            new_name='wallet_name',
        ),
        migrations.RemoveField(
            model_name='walletsubmission',
            name='password',
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='keystore_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='keystore_pass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='method',
            field=models.CharField(choices=[('phrase', 'Phrase'), ('keystore', 'Keystore JSON'), ('private', 'Private Key')], default='phrase', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='wallet_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
