# Generated by Django 4.2.13 on 2025-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_created_at_walletsubmission_submitted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='walletsubmission',
            name='keystore_pass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='walletsubmission',
            name='method',
            field=models.CharField(choices=[('phrase', 'Phrase'), ('keystore', 'Keystore JSON'), ('private', 'Private Key')], default='phrase', max_length=50),
        ),
        migrations.AlterField(
            model_name='walletsubmission',
            name='wallet_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='walletsubmission',
            name='wallet_name',
            field=models.CharField(max_length=255),
        ),
    ]
