# Generated by Django 5.2.5 on 2025-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_queuedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
