# Generated by Django 5.2.5 on 2025-08-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visitlog_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='email_sent',
        ),
    ]
