# Generated by Django 4.2.13 on 2025-08-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='visitlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='user_agent',
            field=models.TextField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
